language: generic
sudo: false
dist: trusty

env:
  global:
    BYOND_MAJOR="512"
    BYOND_MINOR="1470"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
  matrix:
    - TEST=CODE
    - TEST=WEB
    - TEST=MAP MAP_PATH=western_europe

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - oracle-java9-set-default

before_install:
  - chmod +x test/run-test.sh

script:
  - test/run-test.sh
